- name: Apply my fedora config
  hosts: local
  become_user: ismail
  roles:
    - { role: robertdebock.rpmfusion, become: yes}
    - { role: rpm_packages, become: yes } 
    - { role: flathub_packages, become: yes }
    - { role: gantsign.visual-studio-code, become: yes }
    - { role: oefenweb.pycharm, become: yes }
